export const KNOWN_SKILLS = [
  "react",
  "react native",
  "node.js",
  "express",
  "express.js",
  "nestjs",
  "typescript",
  "javascript",
  "python",
  "go",
  "golang",
  "docker",
  "kubernetes",
  "postgresql",
  "mysql",
  "mongodb",
  "redis",
  "jwt",
  "graphql",
  "aws",
  "azure",
  "gcp",
  "c#",
  ".net",
  "prisma",
  "fastapi",
  "flutter",
  "dart",
  "java",
  "ruby",
  "angular",
  "firebase"
];

export const SkillSynonyms: Record<string, string[]> = {
  javascript: ["js"],
  typescript: ["ts"],
  go: ["golang"],
  "node.js": ["node"],
  postgresql: ["postgres", "pgsql"],
  csharp: ["c#"],
  dotnet: [".net", "asp.net"],
  react: ["reactjs", "react.js"],
  vue: ["vuejs", "vue.js"],
  kubernetes: ["k8s"],
  amazon: ["aws"],
  gcp: ["google cloud"],
  azure: ["microsoft azure"],
  "machine learning": ["ml"],
  "deep learning": ["dl"]
};
